CREATE INDEX IF NOT EXISTS route_id_vp_idx ON vehicleposition (route_id);
CREATE INDEX IF NOT EXISTS direction_id_vp_idx ON vehicleposition (direction_id);
CREATE INDEX IF NOT EXISTS journey_start_time_vp_idx ON vehicleposition (journey_start_time);
CREATE INDEX IF NOT EXISTS unique_vehicle_id_vp_idx ON vehicleposition USING brin (unique_vehicle_id);
CREATE INDEX IF NOT EXISTS oday_vp_idx ON vehicleposition USING brin (oday);
CREATE INDEX IF NOT EXISTS lat_vp_idx ON vehicleposition (lat);
CREATE INDEX IF NOT EXISTS long_vp_idx ON vehicleposition (long);
CREATE INDEX IF NOT EXISTS tsi_vp_idx ON vehicleposition (tsi);
CREATE INDEX IF NOT EXISTS next_stop_vp_id_idx ON vehicleposition USING brin (next_stop_id);
CREATE INDEX IF NOT EXISTS stop_id_vp_idx ON vehicleposition (stop);
CREATE INDEX IF NOT EXISTS index10_vp ON vehicleposition (oday, geohash_level, unique_vehicle_id, vehicle_number, owner_operator_id);
CREATE INDEX IF NOT EXISTS journey_type_vp_idx ON vehicleposition (journey_type);
CREATE INDEX IF NOT EXISTS event_type_vp_idx ON vehicleposition (event_type);
CREATE INDEX IF NOT EXISTS area_search_vp_idx ON vehicleposition (tst ASC, lat ASC, long ASC, journey_type, event_type);
CREATE INDEX IF NOT EXISTS route_departures_vp_idx ON vehicleposition (event_type, oday, route_id, direction_id, stop, journey_start_time ASC, unique_vehicle_id ASC, tst DESC);
CREATE INDEX IF NOT EXISTS stop_departure_vp_idx ON vehicleposition (event_type, oday, stop);
CREATE INDEX IF NOT EXISTS unsigned_events_vp_idx ON vehicleposition (tst ASC, journey_type, unique_vehicle_id);

CREATE INDEX IF NOT EXISTS route_id_lp_idx ON lightpriorityevent (route_id);
CREATE INDEX IF NOT EXISTS direction_id_lp_idx ON lightpriorityevent (direction_id);
CREATE INDEX IF NOT EXISTS journey_staart_time_lp_idx ON lightpriorityevent (journey_start_time);
CREATE INDEX IF NOT EXISTS unique_vehicle_id_lp_idx ON lightpriorityevent USING brin (unique_vehicle_id);
CREATE INDEX IF NOT EXISTS oday_lp_idx ON lightpriorityevent USING brin (oday);
CREATE INDEX IF NOT EXISTS lat_lp_idx ON lightpriorityevent (lat);
CREATE INDEX IF NOT EXISTS long_lp_idx ON lightpriorityevent (long);
CREATE INDEX IF NOT EXISTS tsi_lp_idx ON lightpriorityevent (tsi);
CREATE INDEX IF NOT EXISTS next_lp_lpop_id_idx ON lightpriorityevent USING brin (next_stop_id);
CREATE INDEX IF NOT EXISTS stop_lp_id_idx ON lightpriorityevent (stop);
CREATE INDEX IF NOT EXISTS index10_lp ON lightpriorityevent (oday, geohash_level, unique_vehicle_id, vehicle_number, owner_operator_id);
CREATE INDEX IF NOT EXISTS journey_type_lp_idx ON lightpriorityevent (journey_type);
CREATE INDEX IF NOT EXISTS event_type_lp_idx ON lightpriorityevent (event_type);
CREATE INDEX IF NOT EXISTS area_search_lp_idx ON lightpriorityevent (tst ASC, lat ASC, long ASC, journey_type, event_type);
CREATE INDEX IF NOT EXISTS route_departures_lp_idx ON lightpriorityevent (event_type, oday, route_id, direction_id, stop, journey_start_time ASC, unique_vehicle_id ASC, tst DESC);
CREATE INDEX IF NOT EXISTS stop_departure_lp_idx ON lightpriorityevent (event_type, oday, stop);
CREATE INDEX IF NOT EXISTS unsigned_events_lp_idx ON lightpriorityevent (tst ASC, journey_type, unique_vehicle_id);

CREATE INDEX IF NOT EXISTS route_id_oe_idx ON otherevent (route_id);
CREATE INDEX IF NOT EXISTS direction_id_oe_idx ON otherevent (direction_id);
CREATE INDEX IF NOT EXISTS journey_start_time_oe_idx ON otherevent (journey_start_time);
CREATE INDEX IF NOT EXISTS unique_vehicle_id_oe_idx ON otherevent USING brin (unique_vehicle_id);
CREATE INDEX IF NOT EXISTS oday_oe_idx ON otherevent USING brin (oday);
CREATE INDEX IF NOT EXISTS lat_oe_idx ON otherevent (lat);
CREATE INDEX IF NOT EXISTS long_oe_idx ON otherevent (long);
CREATE INDEX IF NOT EXISTS tsi_oe_idx ON otherevent (tsi);
CREATE INDEX IF NOT EXISTS next_oe_stop_id_idx ON otherevent USING brin (next_stop_id);
CREATE INDEX IF NOT EXISTS stop_oe_id_idx ON otherevent (stop);
CREATE INDEX IF NOT EXISTS index10_oe ON otherevent (oday, geohash_level, unique_vehicle_id, vehicle_number, owner_operator_id);
CREATE INDEX IF NOT EXISTS journey_type_oe_idx ON otherevent (journey_type);
CREATE INDEX IF NOT EXISTS event_type_oe_idx ON otherevent (event_type);
CREATE INDEX IF NOT EXISTS area_search_oe_idx ON otherevent (tst ASC, lat ASC, long ASC, journey_type, event_type);
CREATE INDEX IF NOT EXISTS route_departures_oe_idx ON otherevent (event_type, oday, route_id, direction_id, stop, journey_start_time ASC, unique_vehicle_id ASC, tst DESC);
CREATE INDEX IF NOT EXISTS stop_departure_oe_idx ON otherevent (event_type, oday, stop);
CREATE INDEX IF NOT EXISTS unsigned_events_oe_idx ON otherevent (tst ASC, journey_type, unique_vehicle_id);

CREATE INDEX IF NOT EXISTS route_id_st_idx ON stopevent (route_id);
CREATE INDEX IF NOT EXISTS direction_id_st_idx ON stopevent (direction_id);
CREATE INDEX IF NOT EXISTS journey_start_time_st_idx ON stopevent (journey_start_time);
CREATE INDEX IF NOT EXISTS unique_vehicle_id_st_idx ON stopevent USING brin (unique_vehicle_id);
CREATE INDEX IF NOT EXISTS oday_st_idx ON stopevent USING brin (oday);
CREATE INDEX IF NOT EXISTS lat_st_idx ON stopevent (lat);
CREATE INDEX IF NOT EXISTS long_st_idx ON stopevent (long);
CREATE INDEX IF NOT EXISTS tsi_st_idx ON stopevent (tsi);
CREATE INDEX IF NOT EXISTS next_st_stop_id_idx ON stopevent USING brin (next_stop_id);
CREATE INDEX IF NOT EXISTS stop_st_id_idx ON stopevent (stop);
CREATE INDEX IF NOT EXISTS index10_st ON stopevent (oday, geohash_level, unique_vehicle_id, vehicle_number, owner_operator_id);
CREATE INDEX IF NOT EXISTS journey_type_st_idx ON stopevent (journey_type);
CREATE INDEX IF NOT EXISTS event_type_st_idx ON stopevent (event_type);
CREATE INDEX IF NOT EXISTS area_search_st_idx ON stopevent (tst ASC, lat ASC, long ASC, journey_type, event_type);
CREATE INDEX IF NOT EXISTS route_departures_st_idx ON stopevent (event_type, oday, route_id, direction_id, stop, journey_start_time ASC, unique_vehicle_id ASC, tst DESC);
CREATE INDEX IF NOT EXISTS stop_departure_st_idx ON stopevent (event_type, oday, stop);
CREATE INDEX IF NOT EXISTS unsigned_events_st_idx ON stopevent (tst ASC, journey_type, unique_vehicle_id);

CREATE INDEX IF NOT EXISTS route_id_ue_idx ON unsignedevent (route_id);
CREATE INDEX IF NOT EXISTS direction_id_ue_idx ON unsignedevent (direction_id);
CREATE INDEX IF NOT EXISTS journey_start_time_ue_idx ON unsignedevent (journey_start_time);
CREATE INDEX IF NOT EXISTS unique_vehicle_id_ue_idx ON unsignedevent USING brin (unique_vehicle_id);
CREATE INDEX IF NOT EXISTS oday_ue_idx ON unsignedevent USING brin (oday);
CREATE INDEX IF NOT EXISTS lat_ue_idx ON unsignedevent (lat);
CREATE INDEX IF NOT EXISTS long_ue_idx ON unsignedevent (long);
CREATE INDEX IF NOT EXISTS tsi_ue_idx ON unsignedevent (tsi);
CREATE INDEX IF NOT EXISTS next_ue_stop_id_idx ON unsignedevent USING brin (next_stop_id);
CREATE INDEX IF NOT EXISTS stop_ue_id_idx ON unsignedevent (stop);
CREATE INDEX IF NOT EXISTS index10_ue ON unsignedevent (oday, geohash_level, unique_vehicle_id, vehicle_number, owner_operator_id);
CREATE INDEX IF NOT EXISTS journey_type_ue_idx ON unsignedevent (journey_type);
CREATE INDEX IF NOT EXISTS event_type_ue_idx ON unsignedevent (event_type);
CREATE INDEX IF NOT EXISTS area_search_ue_idx ON unsignedevent (tst ASC, lat ASC, long ASC, journey_type, event_type);
CREATE INDEX IF NOT EXISTS route_departures_ue_idx ON unsignedevent (event_type, oday, route_id, direction_id, stop, journey_start_time ASC, unique_vehicle_id ASC, tst DESC);
CREATE INDEX IF NOT EXISTS stop_departure_ue_idx ON unsignedevent (event_type, oday, stop);
CREATE INDEX IF NOT EXISTS unsigned_events_ue_idx ON unsignedevent (tst ASC, journey_type, unique_vehicle_id);